<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_22 Pulman  (Ekonomi) (0)_1</name>
   <tag></tag>
   <elementGuidId>b6e12803-7766-4c2e-ad8d-d8773581a30b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mainTabView:gidisSeferTablosu:3:j_idt109:0:somVagonTipiGidis1_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>983820ef-e72b-415d-a69d-f198af244b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainTabView:gidisSeferTablosu:3:j_idt109:0:somVagonTipiGidis1_label</value>
      <webElementGuid>dcfb97da-8a27-4ea4-a032-a2388007d33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>5a7a8b90-c8d6-4551-a094-8069f0a40830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2+2 Pulman  (Ekonomi) (0)</value>
      <webElementGuid>822e7c2e-bbd3-45a8-b2d7-abcb658feb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainTabView:gidisSeferTablosu:3:j_idt109:0:somVagonTipiGidis1_label&quot;)</value>
      <webElementGuid>fbbe11ea-e700-4d52-81d6-20d8205ecded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label']</value>
      <webElementGuid>cee6bd1b-8d58-4a06-983a-6253be3a4068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
