<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_22 Pulman  (Ekonomi) (0)</name>
   <tag></tag>
   <elementGuidId>69656063-9e2a-4fcf-9b17-0f987e491307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5856f6a3-793a-433a-bd7d-594814f1f770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label</value>
      <webElementGuid>5b7d998d-ba1b-4796-9643-e66e4d27dccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>9d2a9dec-0ab9-4ed1-aaa2-c7628b7655e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2+2 Pulman  (Ekonomi) (0)</value>
      <webElementGuid>950b4041-c068-4385-b6bf-13c934973f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label&quot;)</value>
      <webElementGuid>aaf6d7a0-b26d-4abd-b538-e8f439ee19ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label']</value>
      <webElementGuid>236324bf-6c9b-4a11-8eba-73192551a03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1']/label</value>
      <webElementGuid>fa081ffb-344e-473d-a0ed-33e95de7c2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esnek'])[3]/following::label[1]</value>
      <webElementGuid>2e172c69-ec6d-42b9-9a9b-ed2834a6eeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standart'])[3]/following::label[1]</value>
      <webElementGuid>acb980ad-2bb3-4208-9aef-857dedd17e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₺ 171,00'])[3]/preceding::label[1]</value>
      <webElementGuid>9ce63efb-69a1-4ddd-ab67-b235906bbdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seç'])[3]/preceding::label[2]</value>
      <webElementGuid>4234ff31-ba84-4a71-b1e3-d0edad76f088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/div/label</value>
      <webElementGuid>0ef817f0-c256-44be-89e9-e93cc7abeb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label' and (text() = '2+2 Pulman  (Ekonomi) (0)' or . = '2+2 Pulman  (Ekonomi) (0)')]</value>
      <webElementGuid>ee0ab4e2-1d03-42a8-aae2-2cf22f11b2aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
