<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_21 Pulman (Business) (0)</name>
   <tag></tag>
   <elementGuidId>70b051b7-82ed-42ab-90ce-6f4971e1fe45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9622efdb-cf92-4703-87bf-aaed4c5b3d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label</value>
      <webElementGuid>aac32e15-2416-4c5f-b994-431084ab6832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>5a92c16e-23ff-465d-83e2-739b7f7d9bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2+1 Pulman (Business) (0)</value>
      <webElementGuid>d99a0e4c-87e7-449e-8938-5817ecace3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label&quot;)</value>
      <webElementGuid>860ed8d3-f7f3-45eb-b605-fbdb6c116b24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label']</value>
      <webElementGuid>8b40088f-8a30-4900-8f5b-cb3042572f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1']/label</value>
      <webElementGuid>f7337563-ef6c-404a-a7b3-821dba50b195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esnek'])[3]/following::label[1]</value>
      <webElementGuid>c8d8204f-7e1a-4489-b89f-69cd7eb65838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standart'])[3]/following::label[1]</value>
      <webElementGuid>ea5078f6-5cdc-4f9a-a147-0130fe1d19a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₺ 257,00'])[1]/preceding::label[1]</value>
      <webElementGuid>838af100-d8a8-4869-8f8b-eaf53a803aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seç'])[3]/preceding::label[2]</value>
      <webElementGuid>7b27a70d-9fde-4c8e-811b-81d12252d01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/div/label</value>
      <webElementGuid>a1b46c13-352d-4d47-bf01-61776018ffd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'mainTabView:gidisSeferTablosu:2:j_idt109:0:somVagonTipiGidis1_label' and (text() = '2+1 Pulman (Business) (0)' or . = '2+1 Pulman (Business) (0)')]</value>
      <webElementGuid>3a3d5412-d3e2-45df-8425-124c3d204310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
