<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Devam</name>
   <tag></tag>
   <elementGuidId>b11fbbbb-76db-4688-9727-118fed3a6591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='mainTabView:pgSayfaDegistirme0']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>45b41644-266a-4d96-b9f8-498d7562e3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Devam</value>
      <webElementGuid>d66d25f9-cb63-42b3-ae34-73cb17f85012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainTabView:pgSayfaDegistirme0&quot;)/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>7098d71c-0731-47bc-8962-cf988fa9d85b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mainTabView:pgSayfaDegistirme0']/tbody/tr/td[2]</value>
      <webElementGuid>38029a25-4d3c-41ed-9baa-3c415175d232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geri'])[1]/following::td[1]</value>
      <webElementGuid>35a94aeb-122b-40eb-bf7b-95b8798c3ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('*Planlanan varış saati Tcdd Taşımacılık A.Ş.', &quot;'&quot;, 'nin zaman taahhütlerini içermez*')])[1]/following::td[2]</value>
      <webElementGuid>c9b09d68-306d-4f78-8871-56379214fe7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yolcu Bilgileri'])[1]/preceding::td[1]</value>
      <webElementGuid>375dfd98-ab4f-468a-809a-b82438dd36d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]</value>
      <webElementGuid>20336b31-aa89-4ae8-b894-b3fb547983d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Devam' or . = 'Devam')]</value>
      <webElementGuid>f9597c1d-7035-4659-9991-4432f16962f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
